# Generated by Django 5.0.6 on 2024-06-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=255, unique=True)),
                ('urea_kg_ha', models.CharField(max_length=255)),
                ('tsp_kg_ha', models.CharField(max_length=255)),
                ('mop_kg_ha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farming_Suggesstions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea_kg_ha', models.CharField(max_length=255)),
                ('tsp_kg_ha', models.CharField(max_length=255)),
                ('mop_kg_ha', models.CharField(max_length=255)),
                ('plant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer_brain.plants')),
            ],
        ),
    ]
