# Generated by Django 5.0.6 on 2024-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_brain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farming_suggesstions',
            name='mop_kg_ha',
        ),
        migrations.RemoveField(
            model_name='farming_suggesstions',
            name='tsp_kg_ha',
        ),
        migrations.RemoveField(
            model_name='farming_suggesstions',
            name='urea_kg_ha',
        ),
        migrations.AddField(
            model_name='farming_suggesstions',
            name='sugesstions',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
