# Generated by Django 5.0.6 on 2024-06-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_brain', '0002_remove_farming_suggesstions_mop_kg_ha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farming_suggesstions',
            old_name='sugesstions',
            new_name='suggestions',
        ),
    ]
